# Generated by Django 3.0.3 on 2023-03-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinions',
            name='amount_conts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opinions',
            name='amount_pros',
            field=models.IntegerField(default=0),
        ),
    ]
