# Generated by Django 3.0.3 on 2023-03-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230307_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinions',
            old_name='amount_conts',
            new_name='amount_cons',
        ),
    ]
