# Generated by Django 3.0.3 on 2023-03-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230307_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_stars',
            field=models.FloatField(default=0),
        ),
    ]
