# Generated by Django 3.0.3 on 2023-03-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_avg_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinions',
            name='opinion_id',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
