# Generated by Django 3.0.3 on 2023-03-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_opinions_opinion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinions',
            name='unuseful_counter',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='useful_counter',
            field=models.IntegerField(max_length=200),
        ),
    ]
